#!/usr/bin/env tsx
/**
 * Generate TypeScript definitions for the shellcheck-wasm module.
 *
 * The .wasm file is a WASI *reactor* module (see scripts/build-wasm.sh):
 * call `_initialize` once, then `hs_init(0, 0)`, then `await` the async
 * JSFFI exports. The accompanying dist/shellcheck.js is generated by
 * GHC's post-link.mjs and provides the `ghc_wasm_jsffi` imports.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, '..');
const distDir = resolve(projectRoot, 'dist');

mkdirSync(distDir, { recursive: true });

const dtsContent = `/**
 * TypeScript definitions for the shellcheck-wasm WASI reactor module.
 * Generated by scripts/gen-types.ts
 *
 * Loading sequence (see GHC user's guide, "JavaScript FFI in the wasm
 * backend"):
 *
 *   1. Import the post-link glue: \`const jsffi = (await import('./shellcheck.js')).default(__exports)\`
 *   2. Instantiate with \`{ ghc_wasm_jsffi: jsffi, wasi_snapshot_preview1: wasi.wasiImport }\`
 *   3. Assign exports back: \`Object.assign(__exports, instance.exports)\`
 *   4. Initialize WASI (calls the reactor \`_initialize\` export once)
 *   5. Call \`hs_init(0, 0)\` before any other export
 *   6. \`await instance.exports.lintWithOptions(script, optionsJson)\`
 */

/** Raw exports of the instantiated reactor module. */
export interface ShellCheckWasmExports {
  /** Linear memory shared with the Haskell heap. */
  memory: WebAssembly.Memory;
  /** WASI reactor initializer. Must be called exactly once (usually via the WASI implementation). */
  _initialize(): void;
  /** GHC RTS initializer. Must be called before any lint export. */
  hs_init(argc: number, argv: number): void;
  /**
   * Async JSFFI export. Resolves to a JSON string (array of lint results).
   * Must be awaited.
   */
  lint(script: string): Promise<string>;
  /**
   * Async JSFFI export. Second argument is a JSON-encoded LintOptions
   * object. Resolves to a JSON string (array of lint results).
   */
  lintWithOptions(script: string, optionsJson: string): Promise<string>;
}

/** Options accepted by the lint exports (JSON-encoded). */
export interface LintOptions {
  shell?: 'bash' | 'sh' | 'dash' | 'ksh' | 'busybox';
  severity?: 'error' | 'warning' | 'info' | 'style';
  exclude?: number[];
  include?: number[];
  externalSources?: boolean;
  sourcePaths?: string[];
  /** Virtual files for sourced scripts (path -> content). */
  files?: Record<string, string>;
}

export interface Replacement {
  startLine: number;
  startColumn: number;
  endLine: number;
  endColumn: number;
  text: string;
}

export interface FixInfo {
  replacements: Replacement[];
}

export interface LintResult {
  file: string;
  line: number;
  column: number;
  endLine?: number;
  endColumn?: number;
  code: number;
  severity: 'error' | 'warning' | 'info' | 'style';
  message: string;
  fix?: FixInfo;
}

export type LintResponse = LintResult[] | { error: string };

export interface ShellCheckWasmInstance {
  lint(script: string, options?: LintOptions): Promise<LintResult[]>;
  lintWithOptions(script: string, options: LintOptions): Promise<LintResult[]>;
  terminate(): void;
}

export declare function createShellCheck(options?: {
  wasmUrl?: string;
  runtime?: 'node' | 'browser' | 'auto';
}): Promise<ShellCheckWasmInstance>;

export declare function lint(script: string, options?: LintOptions): Promise<LintResult[]>;

export declare function lintWithOptions(
  script: string,
  options: LintOptions
): Promise<LintResult[]>;

export declare function resetShellCheck(): void;
`;

const outputPath = resolve(distDir, 'shellcheck.d.ts');
writeFileSync(outputPath, dtsContent);
console.log(`Generated ${outputPath}`);
